[bin:vpn] Daemonize openvpn

diff --git a/.bin/vpn b/.bin/vpn
--- a/.bin/vpn
+++ b/.bin/vpn
@@ -10,4 +10,17 @@ if [[ ! -f ~/.config/ovpn/client.ovpn ]]; then
     exit 1
 fi
 
-sudo openvpn --config ~/.config/ovpn/client.ovpn --auth-user-pass
+if [[ -z "$1" ]]; then
+    sudo openvpn --config ~/.config/ovpn/client.ovpn --auth-user-pass --daemon
+elif [[ "$1" = "-k" ]]; then
+    sudo killall openvpn 2>/dev/null
+    if [[ $? = 0 ]]; then
+        echo "Killed OpenVPN daemon"
+    else
+        echo "Could not kill OpenVPN daemon -- it might not be running" 1>&2
+        exit 1
+    fi
+else
+    echo "Usage: $(basename "$0") [-k]" 1>&2
+    exit 1
+fi
