[scripts] make quick-actions more reliably find audio device

diff --git a/scripts/.bin/quick-actions b/scripts/.bin/quick-actions
--- a/scripts/.bin/quick-actions
+++ b/scripts/.bin/quick-actions
@@ -14,6 +14,7 @@ add_opt "Switch sound to speakers" "switch-audo-output 'Pebble V3 Analog Stereo'
 add_opt "Switch sound to headphones" "switch-audo-output 'GA102 High Definition Audio Controller Digital Stereo (HDMI)'"
 add_opt "SSH into VPS" "ssh-into-vps"
 add_opt "Kill PulseAudio" "pulseaudio -k"
+
 # add_opt "Fix webcam" "fix-webcam"
 # add_opt "Screenshot Area" "$HOME/.bin/quick-screenshot"
 
@@ -28,7 +29,7 @@ function switch-audo-output {
   local name="$(pactl list sinks | grep "Description: $description" -B1 | head -n1 | awk '{print $2}')"
   if [ -z "$name" ]; then
     echo "could not find sink matching description '$description'" >&2
-    exit 1
+    return 1
   fi
   echo "$description"
   echo "$name"
@@ -64,4 +65,13 @@ if [ -z "$cmd" ]; then
   exit
 fi
 
-eval "$cmd"
+result="$(eval "$cmd" 2>&1)"
+if [ $? != 0 ]; then
+  if command -v notify-send >/dev/null; then
+    notify-send -i error -u critical "Failed to execute action '$action'" "$result"
+  else 
+    echo "Failed to execute action '$action': $result" >&2
+    exit 1
+  fi
+fi
+
